version: '3'
services:
  wordpress:
    build: ../
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: blog_db_name
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: blog_db_name
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db: